server:
  port: 8888
spring:
  cloud:
    config:
      name: micro-config-template
      profile: dev, qa
---
spring:
  cloud:
    config:
      server:
        git:
          uri: ${git_account}/{application}-{profile}
          username:
          password:
---
root_configs: ${directory_for_root_configs}