---
server:
  port: 8888
spring:
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/javierOramon/configurations-prototype # default
          username: javierOramon
          password: JaviOramon2501.
          search-paths:
            - 'station*'
          repos:
             perf:
                pattern: '*/perf'
                uri: https://github.com/javierOramon/confugarions-prototype-perf.git # alt
                search-paths:
                 - 'station*'
