server:
  port: 8888
spring:
  cloud:
    config:
      name: prototype-config-micro-one
      profile: dev
---
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AlfredoOramon/{application}-{profile}
          repos:
            microservice1:
              pattern: '*/development,*/staging'
              uri: https://github.com/AlfredoOramon/prototype-config-micro-one-dev

            #microservice2:
            #microservice3: