server:
  port: ${server_port}
spring:
  cloud:
    config:
      name: micro-config-template
      profile: dev, qa
---
spring:
  cloud:
    config:
      server:
        git:
          uri: ${git_account}/{application}-${profile_spring_cloud}
          username:
          password:
---
root_configs: ${directory_for_root_configs}